@base_url=http://localhost:3000

###
GET {{base_url}}/health

###
POST  {{base_url}}/auth/register
Content-Type: application/json

{
  "email": "felipemagic7@gmail.com",
  "password": "password123"
}
