### VARIABLES
@base_url=http://localhost:3000
@token={{Login.response.body.token}}


### CONTAINER HEALTH CHECK
GET {{base_url}}/health
Authorization: Bearer {{token}}


### REGISTER
POST  {{base_url}}/auth/register
Content-Type: application/json

{
  "email": "marco7@gmail.com",
  "password": "password123"
}


### LOGIN
# @name Login
POST  {{base_url}}/auth/login
Content-Type: application/json

{
  "email": "marco7@gmail.com",
  "password": "password123"
}


### GET SUBSCRIPTION
GET {{base_url}}/me/subscription
Authorization: Bearer {{token}}


### GET PLANS
GET {{base_url}}/plans  
Authorization: Bearer {{token}}